services:
  - type: web
    name: p7-openc-api
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_api:app --host 0.0.0.0 --port $PORT
